# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'BRD' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
 # use_frameworks!
#  pod 'MLPAutoCompleteTextField'
  # Pods for BRD

  target 'BRDTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BRDUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
